### ISSUE TITLE
E_IOC_LOOKUP_FAILED: Cannot resolve "Adonis/Addons/DynamoDB" namespace from the IoC Container

### ISSUE THREAD

**Issue by jcjp** [Melchyore/adonis-dynamodb#2]
## Prerequisites

- Adonis 5
- adonis-dynamodb

## Description

Encountering error when importing the library itself. Here is how we import the library:

```javascript
import type {Query} from '@ioc:Adonis/Addons/DynamoDB'
import Env from '@ioc:Adonis/Core/Env'
import {DynamoDB} from '@ioc:Adonis/Addons/DynamoDB'
```

This error shows up when using `yarn dev` or running the dev server using `npm`.

~~However when deploying the app on Docker the issue doesn't shows up.~~ I must have been running this on  detached that is why I don't see the Docker error.

## Package version
`"adonis-dynamodb": "^1.2.3"`

## Error Message & Stack Trace
```javascript
[ info ]  re-starting http server...

  IocLookupException 

 E_IOC_LOOKUP_FAILED: Cannot resolve "Adonis/Addons/DynamoDB" namespace from the IoC Container

 at Function.lookupFailed <path>/node_modules/@adonisjs/fold/build/src/Exceptions/IocLookupException.js:18
  13|  /**
  14|   * Raised when unable to lookup a namespace
  15|   */
  16|  class IocLookupException extends utils_1.Exception {
  17|      static lookupFailed(namespace) {
> 18|          return new this(`Cannot resolve "${namespace}" namespace from the IoC Container`, 500, 'E_IOC_LOOKUP_FAILED');
  19|      }
  20|      /**
  21|       * Invalid namespace type
  22|       */
  23|      static invalidNamespace() {

   1  Ioc.lookupOrFail
     <path>/node_modules/@adonisjs/fold/build/src/Ioc/index.js:254

   2  Ioc.use
     <path>/node_modules/@adonisjs/fold/build/src/Ioc/index.js:308

   3  Object.<anonymous>
     <path>/app/DynamoDb/DynamoDb.ts:3

   4  Module._compile
     <path>/node_modules/pirates/lib/index.js:136

   5  Object.newLoader [as .ts]
     <path>/node_modules/pirates/lib/index.js:141

[ warn ]  Underlying HTTP server died with "0 code"
```

## Relevant Information

- See: https://github.com/jcjp/adonis-dynamodb-ioc-issue

**Comment by Melchyore** [comment]
@jcjp Hey!

Did you run `node ace configure adonis-dynamodb` after module installation?

**Comment by jcjp** [comment]
> @jcjp Hey!
> 
> Did you run `node ace configure adonis-dynamodb` after module installation?

~~I added you to my private repo so that you could see the issue,~~ to answer your question yes I run that command on my repository. Our hint is that because I am running or calling the library from the `Providers` files then from there it calls the controller that imports the `Adonis/Addons/DynamoDB` is where the issue lies. BTW thanks for the great library! I made the library public so it will be convienient for you.

**Comment by Melchyore** [comment]
> > @jcjp Hey!
> > 
> > Did you run `node ace configure adonis-dynamodb` after module installation?
> 
> ~~I added you to my private repo so that you could see the issue,~~ to answer your question yes I run that command on my repository. Our hint is that because I am running or calling the library from the `Providers` files then from there it calls the controller that imports the `Adonis/Addons/DynamoDB` is where the issue lies. BTW thanks for the great library! I made the library public so it will be convienient for you.

Thanks for the repo.

Yes, the error comes from the controller that you are importing in your provider.
Top level imports will throw this error everytime you import something from the IoC in a provider file.

But first of all, you should **never** import your controllers, they are meant to be only used by your routes.
Then, if you really want to import your controller, I guess you'll need to pass it from the base provider to your custom class provider. To do that, you need to import it inside the register method.

If it's not clear, please let me know and I'll write a code example as soon as I'm home.

**Comment by jcjp** [comment]
> Yes, the error comes from the controller that you are importing in your provider. Top level imports will throw this error everytime you import something from the IoC in a provider file.
> 
> But first of all, you should **never** import your controllers, they are meant to be only used by your routes. Then, if you really want to import your controller, I guess you'll need to pass it from the base provider to your custom class provider. To do that, you need to import it inside the register method.
> 
> If it's not clear, please let me know and I'll write a code example as soon as I'm home.

Thanks for the prompt response this is how I add it to my base provider:

```javascript
import {ApplicationContract} from '@ioc:Adonis/Core/Application'
import MapController from 'App/Controllers/MQ/MapController'
export default class AppProvider {
  constructor(protected app: ApplicationContract) {}
  public register() {
    this.app.container.singleton('Project/MapController', () => new MapController())
  }
  public async boot() {}
  public async ready() {}
  public async shutdown() {}
}
```

But I'm unsure how would I import it on my provider.

**Comment by Melchyore** [comment]
> 
> Thanks for the prompt response this is how I add it to my base provider:
> 
> ```js
> import {ApplicationContract} from '@ioc:Adonis/Core/Application'
> import MapController from 'App/Controllers/MQ/MapController'
> export default class AppProvider {
>   constructor(protected app: ApplicationContract) {}
>   public register() {
>     this.app.container.singleton('Project/MapController', () => new MapController())
>   }
>   public async boot() {}
>   public async ready() {}
>   public async shutdown() {}
> }
> ```
> 
> But I'm unsure how would I import it on my provider.

Well, as I told you, what you are doing is a very very bad idea. The controllers should never be imported nor instantiated, it's the job of the HTTP server. The error is not related to this lib but to AdonisJS and it's not a bug, it's just that what you are doing is anti-pattern. You will run into many errors doing that.

Maybe tell me what you are trying to achieve and maybe I can help you?

Also, consider watching this awesome video that explains more about IoC and Service Providers: 
[https://adocasts.com/lessons/service-providers-and-the-ioc-container](https://adocasts.com/lessons/service-providers-and-the-ioc-container)

**Comment by jcjp** [comment]
> Well, as I told you, what you are doing is a very very bad idea. The controllers should never be imported nor instantiated, it's the job of the HTTP server. The error is not related to this lib but to AdonisJS and it's not a bug, it's just that what you are doing is anti-pattern. You will run into many errors doing that.
> 
> Maybe tell me what you are trying to achieve and maybe I can help you?
> 
> Also, consider watching this awesome video that explains more about IoC and Service Providers: https://adocasts.com/lessons/service-providers-and-the-ioc-container

I see my code is still wrong, how will I be able to utilize the `MapController` I can't change the structure of the codebase it is what has been designed. How will I pass it from my base provider to the custom class? The `MapController` is just a file or rather a controller that will route the action to the correct controller file.

The actual repository would not be an open API that a client could request using HTTP verbs rather it will just listen to a data coming in, but we still want to utilize the controllers to route data properly.

~~Another info as well it works when running the project on Docker, that error only shows up when running it using the dev script~~. I am also curious as well on your code example.

We got this solved somehow we need to manually import using the require under the custom provider itself where it's used. Feel free to close this ticket as the issue is unrelated to your library. Thanks for your help!

**Comment by Melchyore** [comment]
Please, understand that controllers are **ONLY** meant to be used with routes. Not only your code is wrong, but also the way you want to solve your problem. What kind of data are coming? From where? I can't really help you if you don't give me the information I need.

The controllers are classes where you define functions ONLY to respond to HTTP requests. They CAN'T do another job. You need to change the structure of your codebase, even if it has been designed for that.

If you give me more information, I can give you solutions.

**Comment by jcjp** [comment]
> Please, understand that controllers are **ONLY** meant to be used with routes. Not only your code is wrong, but also the way you want to solve your problem. What kind of data are coming? From where? I can't really help you if you don't give me the information I need.
> 
> The controllers are classes where you define functions ONLY to repond to HTTP requests. They CAN'T do another job. You need to change the structure of your codebase, even if it has been designed for that.
> 
> If you give me more information, I can give you solutions.

So data would be coming from a messaging queue and doesn't need to trigger a controller or endpoint (I didn't do the design and I can't really change it) and after receiving the data, the adonis service will interact with the database. Yes I understand your point of view, if I were to change the implementation what could I replace controller with, my guess is to another provider file as well?

**Comment by Melchyore** [comment]
> So data would be coming from a messaging queue and doesn't need to trigger a controller or endpoint (I didn't do the design and I can't really change it) and after receiving the data, the adonis service will interact with the database. Yes I understand your point of view, if I were to change the implementation what could I replace controller with, my guess is to another provider file as well?

It can be anything else but request-related-files/providers. Are you using RabbitMQ with AdonisJS?

**Comment by jcjp** [comment]
> It can be anything else but request-related-files/providers. Are you using RabbitMQ with AdonisJS?

We use Kafka with Adonis.

**Comment by Melchyore** [comment]
> > It can be anything else but request-related-files/providers. Are you using RabbitMQ with AdonisJS?
> 
> We use Kafka with Adonis.

Adonis V5 doesn't have any community-package for Kafka. So, the best thing you can do is to create a [preload file](https://docs.adonisjs.com/guides/adonisrc-file#preloads). IoC bindings are available in a preload file, so you can import your DynamoDB model and Kafka class. You can also create a provider where you register Kafka as a singleton and import it in your preload file from the IoC.

In the preload file, you will listen to topics:

```ts
import Kafka from '@ioc:Adonis/Kafka' // <-- In case you've registered it in a provider. Or import it as a regular node module.
import Model from 'App/DynamoDB/DynamoDb'

Kafka.on('foo', (message) => {
 // Do something with message
})
```

Of course, you'll need to edit a little bit this code as I've never worked with Kafka, but that's the base idea.

**Comment by jcjp** [comment]
> Adonis V5 doesn't have any community-package for Kafka. So, the best thing you can do is to create a [preload file](https://docs.adonisjs.com/guides/adonisrc-file#preloads). IoC bindings are available in a preload file, so you can import your DynamoDB model and Kafka class. You can also create a provider where you register Kafka as a singleton and import it in your preload file from the IoC.
> 
> In the preload file, you will listen to topics:
> 
> ```ts
> import Kafka from '@ioc:Adonis/Kafka' // <-- In case you've registered it in a provider. Or import it as a regular node module.
> import Model from 'App/DynamoDB/DynamoDb'
> 
> Kafka.on('foo', (message) => {
>  // Do something with message
> })
> ```
> 
> Of course, you'll need to edit a little bit this code as I've never worked with Kafka, but that's the base idea.

Thank you so much for your help and that information I will look into working with that! Feel free to close this question, you are very helpful.
