### ISSUE TITLE
DynamoDB query output returns all properties and values but toJSON doesn't

### ISSUE THREAD

**Issue by jcjp** [Melchyore/adonis-dynamodb#3]
## Prerequisites

- Adonis 5
- adonis-dynamodb

## Description

Has anybody else experienced where in the DynamoDB model doesn't return all properties indicated? I tried console logging the DynamoDB query output and it shows the properties that are missings but when converting the output to JSON it's missing properties. Here is an example:

```JavaScript
...
@DynamoDB.$Table({name: Env.get('TABLE', '')})
export default class DynamoDb extends DynamoDB.Table {
  ...

    @DynamoDB.Attribute.String()
    public name: string

    @DynamoDB.Attribute.String()
    public description: string

    @DynamoDB.Attribute.String()
    public sample: string

    @DynamoDB.Attribute.Any()
    public type: string | number

    @DynamoDB.Attribute.Any()
    public order: string | number

    @DynamoDB.Attribute.Any()
    public sample: string

    @DynamoDB.Attribute.Any() // Even tried StringSet but doesn't work
    public values: Array<string>
  ....
}
```

```JavaScript
// console.log(dynamoOutput)
...
name: {S: 'Test'},
description: {S: 'Test description'},
sample: {S: 'Test example'}, // <-- this is missing when toJSON is called
type: {N: 1}, // <-- this is missing when toJSON is called
...
```

```JavaScript
// console.log(dynamoOutput.toJSON())
{
    name: 'Test',
    description: 'Test description'
}
```

## Package version

`"adonis-dynamodb": "^1.2.3"`

## Error Message & Stack Trace

- No errors just missing properties and values when using `toJSON()`

## Relevant Information

- Data properties and values are present in the database
- Tried to stringify the dynamo query output still missing the other details

**Comment by Melchyore** [comment]
@jcjp Hey!

Can you please show the entire code that's not working? It's hard to debug with only few information.

**Comment by jcjp** [comment]
> @jcjp Hey!
> 
> Can you please show the entire code that's not working? It's hard to debug with only few information.

Sorry but I can't show the entire code maybe I'll create a repository with the bug, but it might take a while. But the gist is that I have a endpoint where I request using GET and use you library to query on our DynamoDB using the model stated above.

Here is a code snippet of the DynamoDB query / get:

```JavaScript
public async items({request, response}: HttpContextContract) {
  const records = await DynamoDb.gsi_id_class.query({
    pid: request.id,
    class: this.class
  })
  response.ok({
    records,
  })
}
```

It returns the items, however they are missing properties from the DynamoDB model / structure. Here is a sample return from DynamoDB query:

```JavaScript
DynamoDb {
  __attributes: {
    description: {
      S: 'Test description.'
    },
    createdAt: { N: '1674708730' },
    class: { S: 'node' },
    sample: {
      S: 'Test sample'
    },
    updatedAt: { N: '1674708730' },
    pid: { S: '0' },
    name: { S: 'Test name' },
    type: { N: '1' },
    values: { L: [Array] },
    id: { S: 'Test id' },
    timestamp: { N: '1674708730' },
    order: { S: 'Unspecified' }
  },
  __original: {},
  __updatedAttributes: [],
  __removedAttributes: [],
  __updateOperators: {},
  __putRequired: false,
  __entireDocumentIsKnown: false
}
```

Here is a sample result of toJSON of that DynamoDB output query above:

```JavaScript
{
  "id": "Test id",
  "pid": "0",
  "timestamp": 1674708730,
  "class": "node",
  "createdAt": 1674708730,,
  "updatedAt": 1674708730,
  "name": "Test name",
  "description": "Test description",
  "version": 1
}
```

**Comment by jcjp** [comment]
Okay I figured it out it seems that when the DynamoDB model is not exact or equal to the type on the database it will not be returned. I think there is an issue with the `.Any()` type since changing them to `.String()` would return the property results. I think this issue is related to  Dyngoose than to this one.

**Comment by Melchyore** [comment]
> Okay I figured it out it seems that when the DynamoDB model is not exact or equal to the type on the database it will not be returned. I think there is an issue with the `.Any()` type since changing them to `.String()` would return the property results. I think this issue is related to Dyngoose than to this one.

Oh, I see. In this case, I'm afraid I can't do anything to fix this issue. I hope the Dyngoose maintainer will fix it.

**Comment by jcjp** [comment]
> 

Thanks I will go on ahead and close this issue.
